# Generated by Django 5.1 on 2025-12-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_membermodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('abs', 'Abs')], max_length=20)),
                ('video_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
