# Generated by Django 5.1 on 2025-12-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='video_url',
        ),
        migrations.AddField(
            model_name='workout',
            name='thumbnail_file',
            field=models.ImageField(blank=True, null=True, upload_to='gymapp/thumbnails/'),
        ),
        migrations.AddField(
            model_name='workout',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='gymapp/videos/'),
        ),
    ]
